title: "Matt Y. Cheung"
title_separator: "|"
logo: "/images/home-solid.png"
masthead_title: " "
search: true
timezone: America/Chicago
baseurl: ""
url: "https://matthewyccheung.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  matthewyccheung

author_profile: true
show_date: true

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "contrast"
plugins:
    - jekyll-include-cache

author:
  name: "Matt Y. Cheung"
  avatar: "/images/me.jpg"
  bio: "PhD Student in Electrical & Computer Engineering working in the areas of Machine Learning Healthcare, Ultrasonic Devices, Wearables and Open-access Healthcare Databases"
  location: "Houston, TX"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matthewyccheung"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=6d3hfUcAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/matthewyccheung/"
    - label: "Email"
      icon: "fas fa-at"
      url: "mailto:mattyc@rice.edu"
