title: "Matt Y. Cheung"
title_separator: "|"
logo: "/images/home-solid.png"
masthead_title: ""
search: true
timezone: America/Chicago
baseurl: ""
url: "https://matthewyccheung.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  matthewyccheung

author_profile: true
show_date: true

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "contrast"
plugins:
    - jekyll-include-cache

author:
  name: "Matt Y. Cheung"
  avatar: "/images/IMG_3972 2 copy.jpg"
  bio: "I'm a PhD student in the Electrical & Computer Engineering Department at Rice University working under Professor [Ashok Veeraraghavan](https://profiles.rice.edu/faculty/ashok-veeraraghavan) in the [Rice Computational Imaging Lab](http://computationalimaging.rice.edu/). By using fundamentals of Wave Optics, DSP and Machine Learning, we co-design design hardware and software to solve real-world problems."
  location: "Houston, TX"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matthewyccheung"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=6d3hfUcAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/matthewyccheung/"
    - label: "Email"
      icon: "fas fa-at"
      url: "mailto:mattyc@rice.edu"
